// ============================================================
// QuickAddSelect — a SearchableSelect with a "+ เพิ่มใหม่" button next
// to it. Clicking it expands a single-field (name-only) inline form
// right there, so picking a site/client/supplier that doesn't exist
// yet doesn't mean cancelling out to go create it on its own page and
// coming back. Only fits entities whose creation needs nothing beyond
// a name (site_number/client_number/supplier_number etc. are all
// auto-generated by a DB trigger) -- cheques need their own richer
// inline form (see Expenses.jsx) since they need more than a name.
// ============================================================
import { useState } from 'react'
import { supabase } from '../lib/supabase.js'
import SearchableSelect from './SearchableSelect.jsx'

export default function QuickAddSelect({
  value, onChange, options, placeholder, required, disabled,
  table, extraPayload, onCreated,
  addLabel = '+ เพิ่มใหม่', namePlaceholder = 'ชื่อ',
}) {
  const [showCreate, setShowCreate] = useState(false)
  const [name, setName] = useState('')
  const [saving, setSaving] = useState(false)

  const handleCreate = async () => {
    if (!name.trim()) return
    setSaving(true)
    try {
      const { data, error } = await supabase.from(table)
        .insert({ name: name.trim(), ...extraPayload })
        .select().single()
      if (error) throw error
      onChange(data.id)
      setShowCreate(false)
      setName('')
      onCreated?.(data)
    } catch (e) { alert('Error: ' + e.message) }
    finally { setSaving(false) }
  }

  return (
    <div>
      <div style={{ display: 'flex', gap: 6 }}>
        <div style={{ flex: 1, minWidth: 0 }}>
          <SearchableSelect value={value} onChange={onChange} options={options} placeholder={placeholder} required={required} disabled={disabled} />
        </div>
        <button type="button" className="btn btn-ghost btn-sm" style={{ flexShrink: 0 }} onClick={() => setShowCreate(s => !s)}>
          {addLabel}
        </button>
      </div>
      {showCreate && (
        <div className="card" style={{ padding: 10, marginTop: 8, display: 'flex', gap: 8, alignItems: 'center' }}>
          <input
            className="input input-sm" style={{ flex: 1 }} autoFocus
            value={name} onChange={e => setName(e.target.value)} placeholder={namePlaceholder}
            onKeyDown={e => { if (e.key === 'Enter') { e.preventDefault(); handleCreate() } }}
          />
          <button type="button" className="btn btn-ghost btn-sm" onClick={() => { setShowCreate(false); setName('') }}>ยกเลิก</button>
          <button type="button" className="btn btn-primary btn-sm" disabled={saving || !name.trim()} onClick={handleCreate}>
            {saving ? '⏳...' : '✅ เพิ่ม'}
          </button>
        </div>
      )}
    </div>
  )
}
