// ============================================================
// QuickAddSelect — a SearchableSelect with a "+ เพิ่มใหม่" button next
// to it. Clicking it expands a name (+ optional single extraField, e.g.
// a category picker) inline form right there, so picking a
// site/client/supplier/inventory item that doesn't exist yet doesn't mean
// cancelling out to go create it on its own page and coming back. Fits
// entities whose creation needs a name plus at most one more field
// (site_number/client_number/supplier_number/inventory code are all
// auto-generated by a DB trigger) -- cheques need their own richer
// multi-field inline form (see Expenses.jsx) since they need more than that.
// ============================================================
import { useState } from 'react'
import { supabase } from '../lib/supabase.js'
import SearchableSelect from './SearchableSelect.jsx'

// Loose "might be the same thing" check -- bidirectional substring,
// case-insensitive, trimmed. Not fuzzy matching; just enough to catch the
// common near-duplicate case (typo, extra spec text, reordered words in
// a longer name) before it becomes a second row for the same real item.
function findPossibleDuplicates(options, typedName) {
  const needle = typedName.trim().toLowerCase()
  if (!needle) return []
  return options.filter(o => {
    const label = (o.label || '').toLowerCase()
    return label.includes(needle) || needle.includes(label)
  })
}

export default function QuickAddSelect({
  value, onChange, options, placeholder, required, disabled,
  table, extraPayload, onCreated,
  addLabel = '+ เพิ่มใหม่', namePlaceholder = 'ชื่อ', initialName = '',
  // Optional single extra field for entities that need one thing beyond a
  // name (e.g. inventory_items' category_id, which the auto-code DB
  // trigger reads to generate a prefixed code -- see
  // generate_inventory_item_code() in
  // supabase/migrations/2026-09-10-02-inventory-item-auto-code.sql).
  // { key, label, options } -- options is [{value, label}], same shape
  // SearchableSelect already expects everywhere else in this app. Never
  // required: leaving it unset just means the created row gets that
  // column left at its default (e.g. no category), same as before this
  // prop existed.
  extraField,
}) {
  const [showCreate, setShowCreate] = useState(false)
  const [name, setName] = useState(initialName)
  const [extraValue, setExtraValue] = useState('')
  const [saving, setSaving] = useState(false)
  const [duplicates, setDuplicates] = useState(null) // null = not checked yet this attempt

  const doCreate = async () => {
    setSaving(true)
    try {
      const { data, error } = await supabase.from(table)
        .insert({ name: name.trim(), ...extraPayload, ...(extraField && extraValue ? { [extraField.key]: extraValue } : {}) })
        .select().single()
      if (error) throw error
      onChange(data.id)
      setShowCreate(false)
      setName('')
      setExtraValue('')
      setDuplicates(null)
      onCreated?.(data)
    } catch (e) { alert('Error: ' + e.message) }
    finally { setSaving(false) }
  }

  const handleCreate = async () => {
    if (!name.trim()) return
    // First press: check for an existing entry that might be this same
    // thing under a different name/typo, and surface it instead of
    // creating right away. Second press (duplicates already shown and
    // the user still wants to proceed) creates for real.
    if (duplicates === null) {
      const found = findPossibleDuplicates(options, name)
      if (found.length) { setDuplicates(found); return }
    }
    await doCreate()
  }

  const useDuplicate = (opt) => {
    onChange(opt.value)
    setShowCreate(false)
    setName('')
    setExtraValue('')
    setDuplicates(null)
  }

  // Re-seeds `name` from the current `initialName` prop every time the
  // create box is opened -- a plain useState(initialName) only captures
  // the prop's value at mount, so without this, a line item's description
  // typed/changed after this component first rendered would never reach
  // the create box (React's classic "initial value" trap).
  const toggleCreate = () => setShowCreate(s => {
    const next = !s
    if (next) { setName(initialName); setExtraValue(''); setDuplicates(null) }
    return next
  })

  return (
    <div>
      <div style={{ display: 'flex', gap: 6 }}>
        <div style={{ flex: 1, minWidth: 0 }}>
          <SearchableSelect value={value} onChange={onChange} options={options} placeholder={placeholder} required={required} disabled={disabled} />
        </div>
        <button type="button" className="btn btn-ghost btn-sm" style={{ flexShrink: 0 }} onClick={toggleCreate}>
          {addLabel}
        </button>
      </div>
      {showCreate && (
        <div className="card" style={{ padding: 10, marginTop: 8, display: 'grid', gap: 8 }}>
          <div style={{ display: 'flex', gap: 8, alignItems: 'center' }}>
            <input
              className="input input-sm" style={{ flex: 1 }} autoFocus
              value={name} onChange={e => { setName(e.target.value); setDuplicates(null) }} placeholder={namePlaceholder}
              onKeyDown={e => { if (e.key === 'Enter') { e.preventDefault(); handleCreate() } }}
            />
            <button type="button" className="btn btn-ghost btn-sm" onClick={() => { setShowCreate(false); setName(''); setExtraValue(''); setDuplicates(null) }}>ยกเลิก</button>
            <button type="button" className="btn btn-primary btn-sm" disabled={saving || !name.trim()} onClick={handleCreate}>
              {saving ? '⏳...' : duplicates?.length ? '✅ สร้างใหม่จริง (ไม่ซ้ำ)' : '✅ เพิ่ม'}
            </button>
          </div>
          {extraField && (
            <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
              <span style={{ fontSize: 12, color: 'var(--text3)', flexShrink: 0 }}>{extraField.label}</span>
              <select className="input input-sm" style={{ flex: 1 }} value={extraValue} onChange={e => setExtraValue(e.target.value)}>
                <option value="">— ไม่ระบุ —</option>
                {extraField.options.map(o => <option key={o.value} value={o.value}>{o.label}</option>)}
              </select>
            </div>
          )}
          {duplicates?.length > 0 && (
            <div style={{ marginTop: 8, fontSize: 12.5 }}>
              <div style={{ color: 'var(--amber, #d9a441)', marginBottom: 4 }}>⚠️ พบรายการที่ชื่อใกล้เคียงกันอยู่แล้ว — กดเลือกถ้าเป็นรายการเดียวกัน ไม่งั้นกด "สร้างใหม่จริง" อีกครั้ง</div>
              <div style={{ display: 'flex', flexWrap: 'wrap', gap: 6 }}>
                {duplicates.map(o => (
                  <button key={o.value} type="button" className="btn btn-sm btn-ghost" style={{ borderColor: 'var(--border)' }} onClick={() => useDuplicate(o)}>
                    {o.label}
                  </button>
                ))}
              </div>
            </div>
          )}
        </div>
      )}
    </div>
  )
}
