-- supabase/migrations/2026-09-03-07-protect-admin-ot-from-checkout-clobber.sql
--
-- Follow-up fixes from the WHOLE-BRANCH review of the worker check-in/check-out
-- feature (not part of the original 7-task plan in
-- docs/superpowers/plans/2026-09-01-worker-checkin-checkout.md). Both statements
-- below re-issue functions first created in
-- 2026-09-03-02-worker-checkin-functions.sql; that file has been updated
-- in-place to the corrected version too, so it stays the single clean
-- definition of these functions.
--
-- Fix A -- perform_worker_checkout's auto-OT upsert clobbered admin-entered OT.
-- The ON CONFLICT (worker_id, date) DO UPDATE overwrote ANY existing worker_ot
-- row for that worker/day, including one an admin typed in via CellEditPopup
-- (real hours, real money). It now only overwrites a row that was itself
-- auto-generated by a prior checkout, identified by the exact sentinel note
-- 'auto จากเช็คเอาท์' that src/pages/assign/TodayCheckinCard.jsx writes. If an
-- admin already has real OT for that worker/day (any other notes value, NULL
-- included), the auto-OT silently no-ops -- the checkout itself still succeeds,
-- the worker just doesn't see an auto-OT entry land on top of the admin's.
--
-- KNOWN, DELIBERATELY PARKED: two auto-generated entries for the same worker on
-- the same day (two different sites) still clobber each other. Accumulating them
-- needs a product decision and is explicitly out of scope here.
--
-- Fix B -- haversine_distance_m had no SET search_path, which Supabase's
-- security advisor flags as function_search_path_mutable. Same cleanup this repo
-- already applied in 2026-08-16-05-security-advisor-fixes.sql.

CREATE OR REPLACE FUNCTION haversine_distance_m(lat1 NUMERIC, lng1 NUMERIC, lat2 NUMERIC, lng2 NUMERIC)
RETURNS NUMERIC
LANGUAGE sql
IMMUTABLE
SET search_path = public
AS $$
  -- Standard haversine formula, earth radius 6371000m. Returns meters.
  SELECT 6371000 * 2 * asin(sqrt(
    sin(radians(lat2 - lat1) / 2) ^ 2 +
    cos(radians(lat1)) * cos(radians(lat2)) * sin(radians(lng2 - lng1) / 2) ^ 2
  ));
$$;

CREATE OR REPLACE FUNCTION perform_worker_checkout(
  p_site_id UUID, p_lat NUMERIC, p_lng NUMERIC,
  p_ot_start TIME DEFAULT NULL, p_ot_end TIME DEFAULT NULL,
  p_ot_hours NUMERIC DEFAULT NULL, p_ot_is_overnight BOOLEAN DEFAULT false, p_ot_notes TEXT DEFAULT NULL
)
RETURNS TABLE(success BOOLEAN, distance_m NUMERIC, radius_m NUMERIC, message TEXT)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_tenant_id UUID := current_tenant_id();
  v_worker_id UUID;
  v_site_lat NUMERIC;
  v_site_lng NUMERIC;
  v_radius NUMERIC;
  v_distance NUMERIC;
  v_today DATE := CURRENT_DATE;
BEGIN
  SELECT id INTO v_worker_id FROM workers WHERE email = auth.email() AND tenant_id = v_tenant_id;
  IF v_worker_id IS NULL THEN
    RETURN QUERY SELECT false, NULL::NUMERIC, NULL::NUMERIC, 'ไม่พบข้อมูลพนักงานที่ผูกกับบัญชีนี้'::TEXT;
    RETURN;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM worker_checkins
    WHERE worker_id = v_worker_id AND site_id = p_site_id AND date = v_today AND tenant_id = v_tenant_id
  ) THEN
    RETURN QUERY SELECT false, NULL::NUMERIC, NULL::NUMERIC, 'ยังไม่ได้เช็คอินวันนี้ — เช็คอินก่อนจึงจะเช็คเอาท์ได้'::TEXT;
    RETURN;
  END IF;

  SELECT lat, lng INTO v_site_lat, v_site_lng FROM sites WHERE id = p_site_id AND tenant_id = v_tenant_id;
  IF v_site_lat IS NULL OR v_site_lng IS NULL THEN
    RETURN QUERY SELECT false, NULL::NUMERIC, NULL::NUMERIC, 'ไซท์งานนี้ยังไม่ได้ตั้งพิกัด — ติดต่อสำนักงาน'::TEXT;
    RETURN;
  END IF;

  SELECT COALESCE((SELECT value::numeric FROM app_settings WHERE tenant_id = v_tenant_id AND key = 'checkin_radius_m'), 200)
    INTO v_radius;
  v_distance := haversine_distance_m(p_lat, p_lng, v_site_lat, v_site_lng);

  IF v_distance > v_radius THEN
    RETURN QUERY SELECT false, v_distance, v_radius,
      format('คุณอยู่ห่างจากไซท์งาน %s เมตร ต้องอยู่ในระยะ %s เมตรจึงจะเช็คเอาท์ได้', round(v_distance), round(v_radius))::TEXT;
    RETURN;
  END IF;

  UPDATE worker_checkins
  SET checkout_at = now(), checkout_lat = p_lat, checkout_lng = p_lng, checkout_distance_m = v_distance
  WHERE worker_id = v_worker_id AND site_id = p_site_id AND date = v_today AND tenant_id = v_tenant_id;

  -- OT fields are optional -- the frontend (Task 7) decides whether the
  -- checkout time crosses the regular-shift-end setting and only passes
  -- these when it does. Trust level here matches admin-typed OT today
  -- (CellEditPopup.jsx): the number isn't re-derived server-side from
  -- p_ot_start/p_ot_end, same as an admin's manual entry isn't either.
  --
  -- The DO UPDATE ... WHERE guard (added 2026-09-03-07) means an auto-OT entry
  -- can only ever overwrite ANOTHER auto-OT entry, identified by the exact
  -- sentinel note TodayCheckinCard.jsx writes. Admin-entered OT for the same
  -- worker/day -- any other notes value, NULL included -- is left completely
  -- alone and the insert silently no-ops; the checkout itself still succeeds.
  -- KNOWN, DELIBERATELY PARKED: two auto entries for the same worker on the
  -- same day (two different sites) still clobber each other.
  IF p_ot_hours IS NOT NULL THEN
    INSERT INTO worker_ot (worker_id, site_id, date, start_time, end_time, ot_hours, is_overnight, notes, tenant_id)
    VALUES (v_worker_id, p_site_id, v_today, p_ot_start, p_ot_end, p_ot_hours, p_ot_is_overnight, p_ot_notes, v_tenant_id)
    ON CONFLICT (worker_id, date) DO UPDATE
      SET site_id = EXCLUDED.site_id, start_time = EXCLUDED.start_time, end_time = EXCLUDED.end_time,
          ot_hours = EXCLUDED.ot_hours, is_overnight = EXCLUDED.is_overnight, notes = EXCLUDED.notes
      WHERE worker_ot.notes = 'auto จากเช็คเอาท์';
  END IF;

  RETURN QUERY SELECT true, v_distance, v_radius, 'เช็คเอาท์สำเร็จ'::TEXT;
END;
$$;

REVOKE EXECUTE ON FUNCTION perform_worker_checkout(UUID, NUMERIC, NUMERIC, TIME, TIME, NUMERIC, BOOLEAN, TEXT) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION perform_worker_checkout(UUID, NUMERIC, NUMERIC, TIME, TIME, NUMERIC, BOOLEAN, TEXT) TO authenticated;
